[workspace]
members = ["packages/*"]
resolver = "2"

[workspace.package]
edition = "2021"
homepage = "https://mantra.zone"
license = "MPL-2"
repository = "https://github.com/MANTRA-Chain/mantra-rust"
publish = false
authors = [
    "MANTRA Engineering Team <tech@mantrachain.io>",
    "Javier C <javier.m.costa@mantra.finance"
]

[workspace.dependencies]
mantra-dex-std = { path = "packages/mantra-dex-std" }

cosmwasm-std = { version = "2.1.3", default-features = true, features = [
    "cosmwasm_2_1",
    "stargate",
] }
cosmwasm-schema = { version = "2.1.3" }
cw-storage-plus = { version = "2.0.0" }
cw-ownable = { version = "2.1.0" }
anyhow = { version = "1.0.71" }
schemars = { version = "0.8.12" }
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
cw-multi-test = { version = "2.1.1", features = [
    "cosmwasm_2_0",
    "staking",
    "stargate",
] }
osmosis-std = { version = "0.26.0" }
uint = { version = "0.10.0" }
anybuf = { version = "0.5.0" }
test-case = { version = "3.3.1" }

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
