[package]
name = "mantra-utils"
version = "1.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords = ["mantrachain", "mantra", "utils", "cosmwasm"]
description = "Utils used by CosmWasm smart contracts on MANTRA Chain"

[dependencies]
cosmwasm-std.workspace = true
cw-ownable.workspace = true
