[package]
authors.workspace    = true
description          = "Utils used by CosmWasm smart contracts on MANTRA Chain"
edition.workspace    = true
homepage.workspace   = true
keywords             = ["mantrachain", "mantra", "utils", "cosmwasm"]
license.workspace    = true
name                 = "mantra-utils"
repository.workspace = true
version              = "1.1.1"

[dependencies]
cosmwasm-std.workspace = true
cw-ownable.workspace   = true
